spring.application.name=KiddieLine
spring.mongodb.host=localhost
spring.mongodb.port=27017
spring.mongodb.database=tinysteps
spring.mongodb.username=root
spring.mongodb.password=secretpassword
spring.mongodb.authentication-database=admin